[window]
padding = { x = 16, y = 16 }
dynamic_padding = true
opacity = 0.875
blur = true

[font]
normal = { family = "Fira Code", style = "Regular" }
size = 12

[colors.cursor]
text = "CellBackground"
cursor = "#f68d2e"

[colors.selection]
text = "#ffffff"
background = "#464c91"

[colors.primary]
foreground = "#c7c7c7"
background = "#000000"

[colors.search.matches]
foreground = "CellBackground"
background = "#ebc17f"

[colors.search.focused_match]
foreground = "CellBackground"
background = "#f68d2e"

[colors.hints.start]
foreground = "CellBackground"
background = "#f68d2e"

[colors.hints.end]
foreground = "CellBackground"
background = "#ebc17f"

[colors.normal]
black = "#1f1f1f"
red = "#9f4845"
green = "#94a862"
yellow = "#ebc17f"
blue = "#759db2"
magenta = "#a2779c"
cyan = "#86bdaa"
white = "#e0e0e0"

[colors.bright]
black = "#3a3a3a"
red = "#e63230"
green = "#a8c467"
yellow = "#f0a74b"
blue = "#7eb1ce"
magenta = "#c784bf"
cyan = "#89c4b7"
white = "#ffffff"

[cursor.style]
shape = "Block"
blinking = "On"
